name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Puedes cambiar esto por la rama que quieras usar para el despliegue

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Versión de Node.js que estás usando

      - name: Install dependencies
        run: npm install  # Instala las dependencias del proyecto

      - name: Build project
        run: npm run build  # Ejecuta la construcción del proyecto Astro

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Usa el token de GitHub
          publish_dir: ./dist  # Carpeta donde Astro genera los archivos construidos
